repos:
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.224
    hooks:
      - id: ruff
        args:
          - --fix
          - --force-exclude
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
        exclude: (docs/conf.py)
      - id: check-json
      - id: check-yaml
      - id: debug-statements
        exclude: (tests/messages/data/)
      - id: end-of-file-fixer
        exclude: (tests/messages/data/)
      - id: name-tests-test
        args: [ '--django' ]
        exclude: (tests/messages/data/)
      - id: requirements-txt-fixer
      - id: trailing-whitespace
