repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files
      - id: check-docstring-first
        exclude: (docs/conf.py)
      - id: check-json
      - id: check-yaml
      - id: debug-statements
        exclude: (tests/messages/data/)
      - id: end-of-file-fixer
        exclude: (tests/messages/data/)
      - id: name-tests-test
        args: [ '--django' ]
        exclude: (tests/messages/data/)
      - id: requirements-txt-fixer
      - id: trailing-whitespace
  - repo: https://github.com/ikamensh/flynt
    rev: "0.77"
    hooks:
      - id: flynt
        exclude: (tests/messages/data/)
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
      - id: autoflake
        exclude: (tests/messages/data/)
        args:
          - --in-place
          - --remove-all-unused-imports
          - --remove-duplicate-keys
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: 'v2.0.1'
    hooks:
      - id: autopep8
        exclude: (tests/messages/data/|docs/conf.py)
        args:
          - --in-place
          - --ignore=E501,E731,E402
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [ --py37-plus ]
        exclude: (tests/messages/data/)
