dist: xenial
language: python

# Use travis docker infrastructure for greater speed
sudo: false

cache:
  directories:
  - cldr
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

matrix:
  include:
    - os: linux
      python: 2.7
    - os: linux
      python: 2.7
      env:
      - CDECIMAL=m3-cdecimal
    - os: linux
      dist: trusty
      python: pypy
    - os: linux
      dist: trusty
      python: pypy3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
      env:
      - PYTHON_TEST_FLAGS=-bb
    - os: linux
      python: 3.6
    - os: linux
      python: 3.7
    - os: linux
      python: 3.8

install:
  - bash .ci/deps.${TRAVIS_OS_NAME}.sh
  - pip install --upgrade pip
  - pip install --upgrade $CDECIMAL pytest==4.3.1 pytest-cov==2.6.1 freezegun==0.3.12 backports.zoneinfo;python_version<"3.9"
  - pip install --editable .

script:
  - make test-cov
  - bash .ci/deploy.${TRAVIS_OS_NAME}.sh

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
