language: python

python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.3"

install:
  - pip install --upgrade pip
  - pip install pytest pytest-cov
  - pip install --editable .

# Use travis docker infrastructure for greater speed
sudo: false

script:
  - make test-cov
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#pocoo"
    on_success: change
    on_failure: always
    use_notice: true
    skip_join: true
