name: CI
"on":
  push:
    branches:
      - master
      - '*-maint'
  pull_request:
    branches:
      - master
      - '*-maint'
jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/setup.py"
      - run: pip install build -e .
      - run: make import-cldr
      - run: python -m build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist
